# Generated by Django 6.0.1 on 2026-02-08 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('authentication', '0019_remove_employer_location_location_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='application_cvs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='salary_expect',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='application',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='authentication.employee'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('waited', 'Waited'), ('to_interview', 'To_interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='waited', max_length=20),
        ),
    ]
