# Generated by Django 6.0.1 on 2026-02-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_cv_file_application_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_archived_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
