# Generated by Django 6.0.1 on 2026-01-21 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_address', models.TextField(help_text='House No, Street Name, Ward, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('no_of_employee', models.CharField(choices=[('1-5', '1-5'), ('6-10', '6-10'), ('11-20', '11-20'), ('21-50', '21-50'), ('51-100', '51-100'), ('101-200', '101-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000'), ('5001-10000', '5001-10000'), ('10001-20000', '10001-20000'), ('20000+', 'More than 20000')], default='1-5', max_length=20)),
                ('founded_at', models.DateField()),
                ('what_we_do', models.TextField()),
                ('why_join_us', models.TextField()),
                ('mission_vision', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.state'),
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='townships', to='authentication.state')),
            ],
            options={
                'unique_together': {('state', 'name')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='township',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.township'),
        ),
    ]
