# Generated by Django 6.0.1 on 2026-01-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_location_state_employer_location_state_township_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='township',
            options={'ordering': ['name']},
        ),
    ]
