# Generated by Django 6.0.1 on 2026-01-24 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_township_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='employee/profiles/pics/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='employee/profiles/cvs/')),
                ('salary_expect', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('Township', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.township')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
