# Generated by Django 6.0.1 on 2026-01-25 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_employee_user_alter_employer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Township',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.township'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.state'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_employee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.location'),
        ),
    ]
