# Generated by Django 6.0.1 on 2026-01-25 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_employee_is_active_employer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='founded_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.location'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='mission_vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='what_we_do',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='why_join_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
