# Generated by Django 6.0.1 on 2026-01-26 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_employee_email_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Township',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.township'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.state'),
        ),
    ]
