# Generated by Django 6.0.1 on 2026-01-31 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_township_employee_township_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.state'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.township'),
        ),
    ]
