# Generated by Django 6.0.1 on 2026-02-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_employee_state_alter_employee_township'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='contact_email',
        ),
    ]
