# Generated by Django 6.0.1 on 2026-02-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_rename_email_employee_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='contact_email',
            new_name='email',
        ),
    ]
