# Generated by Django 6.0.1 on 2026-02-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_rename_contact_email_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
