# Generated by Django 6.0.1 on 2026-02-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_employer_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='profile_photo',
            new_name='company_logo',
        ),
    ]
