# Generated by Django 6.0.1 on 2026-02-01 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_rename_profile_photo_employer_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='employer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='authentication.employer'),
        ),
    ]
