# Generated by Django 6.0.1 on 2026-02-27 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_state_created_at_state_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='township',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='township',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
