# Generated by Django 6.0.1 on 2026-01-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0002_jobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_category',
        ),
    ]
