# Generated by Django 6.0.1 on 2026-01-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0003_remove_jobpost_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
