# Generated by Django 6.0.1 on 2026-01-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0004_jobpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default='company_name', max_length=255),
            preserve_default=False,
        ),
    ]
