# Generated by Django 6.0.1 on 2026-01-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0005_jobpost_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company_name',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='detail_address',
            field=models.TextField(blank=True, help_text='Enter the specific building number, street, or directions.', null=True),
        ),
    ]
