# Generated by Django 6.0.1 on 2026-01-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0006_remove_jobpost_company_name_jobpost_detail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default='company name', max_length=255),
            preserve_default=False,
        ),
    ]
