# Generated by Django 6.0.1 on 2026-02-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0007_jobpost_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='detail_address',
        ),
    ]
