# Generated by Django 6.0.1 on 2026-02-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0008_remove_jobpost_detail_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company_name',
        ),
    ]
