# Generated by Django 6.0.1 on 2026-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0009_remove_jobpost_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20),
        ),
    ]
