# Generated by Django 6.0.1 on 2026-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0010_jobpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
