# Generated by Django 6.0.1 on 2026-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0011_jobpost_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='published', max_length=20),
        ),
    ]
